- name: "nginx | nginx | copy environment"
  become: true
  template:
    src: default
    dest: "{{ nginx_config_dir}}"

- name: "nginx | nginx | copy index.html"
  become: true
  template:
    src: index.html
    dest: "{{ nginx_html_dir}}"

- name: nginx | nginx | Enable service nginx
  become: true
  service:
    name: nginx
    enabled: yes

- name: nginx | nginx | Restart service nginx
  become: true
  service:
    name: nginx
    state: restarted