- name: "datahub | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: serial_data
    clean_install: "{{global_clean_all}}"
    datahub_base_dir: /opt/datahub
    datahub_repo: https://github.com/hias222/datahub.git


- name: "datahub | remove dir {{datahub_base_dir}}"
  become: true
  file:
    path: "{{ datahub_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "datahub | create dir {{ datahub_base_dir}}"
  become: true
  file:
    path: "{{ datahub_base_dir}}"
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'

- name: "datahub | git checkout {{datahub_repo}}"
  git:
    repo: "{{datahub_repo}}"
    dest: "{{ datahub_base_dir}}"
    force: yes

- name: "datahub | Install {{ datahub_base_dir}} packages"
  npm:
    path: "{{ datahub_base_dir}}"
    state: latest


- name: "datahub | create dir {{ datahub_base_dir}}"
  become: true
  file:
    path: "{{ datahub_base_dir}}/env"
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'

- name: "datahub | env | copy environment"
  template:
    src: production.env
    dest: "{{ datahub_base_dir}}/env"

- name: "datahub | build {{ datahub_base_dir}}"
  shell: 
    cmd: npm run build
    chdir: "{{ datahub_base_dir}}"


- name: "datahub | create dir {{ nginx_html_dir }}/datahub"
  become: true
  file:
    path: "{{ nginx_html_dir}}/datahub"
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'
  
- name: "datahub | copy files to nginx {{ nginx_html_dir}}/datahub"
  shell: 
    cmd: "cp -R * {{ nginx_html_dir}}/datahub"
    chdir: "{{ datahub_base_dir}}/dist"

