- name: serial | set vars
  set_fact:
    key_value: serial_data
    serial_base_dir: /opt/colorado/serial
    serial_build_dir: /opt/colorado/build
    pogio_master_file: pigpio-master.zip
    pigpio_base_dir: /opt/colorado/pigpio

- name: serial | set vars
  set_fact:
    key_value: serial_data
    serial_executable_dir: "{{serial_base_dir}}/binaries/aarch64"

# comdline.txt -relaxed
# net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4  elevator=deadline rootwait fixrtc iomem=relaxed
#wget https://github.com/joan2937/pigpio/archive/master.zip
#unzip master.zip
#cd pigpio-master
#make
#sudo make install

- name: "serial | create dir {{ pigpio_base_dir}}"
  become: true
  file:
    path: "{{ pigpio_base_dir}}"
    owner: root
    group: root
    state: directory
    mode: '0755'
  when: install_gpio_libs|bool

- name: serial | copy pigpio
  become: true 
  unarchive:
    src: "{{ pogio_master_file }}"
    dest: "{{pigpio_base_dir}}"
  when: install_gpio_libs|bool

- name: "serial | install pigpio"
  become: true
  shell: | 
    cd {{pigpio_base_dir}}/pigpio-master
    make
    make install
  when: install_gpio_libs|bool

- name: serial | disable service serial
  become: true
  service:
    name: colorado
    enabled: no
  ignore_errors: true

- name: serial | disable service serial
  become: true 
  shell: rm -f /etc/systemd/system/colorado.service
  ignore_errors: true

- name: "serial | reboot"
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  ignore_errors: true

- name: "serial | install service "
  become: true
  template:
    src: colorado.service
    dest: /lib/systemd/system/colorado.service
    owner: root
    group: root
    mode: '0644'
  when: not use_ftdi_serial|bool

- name: "serial | install service for ftdi "
  become: true
  template:
    src: colorado_ftdi.service
    dest: /lib/systemd/system/colorado.service
    owner: root
    group: root
    mode: '0644'
  when: use_ftdi_serial|bool

- name: "serial | install service for linux base "
  become: true
  template:
    src: colorado_linux.service
    dest: /lib/systemd/system/colorado.service
    owner: root
    group: root
    mode: '0644'
  when:
      - ansible_facts['architecture'] == "x86_64"
      - ansible_facts['system'] == "Linux"

- name: "serial | serialsw"
  import_role: 
    name: serialsw

- name: serial | Enable service colorado
  become: true
  service:
    name: colorado
    enabled: yes

- name: serial | Enable service serial
  become: true
  service:
    name: colorado
    state: started

# install -v -m 744 files/colorado.service "${ROOTFS_DIR}/etc/systemd/system"
