
- name: "datamapping | {{datamapping_name}} | pm2"
  command: pm2 delete app.js --name "{{ datamapping_name }}"
  args:
    chdir: "{{ datamapping_base_dir}}"
  ignore_errors: true

- name: "datamapping | {{datamapping_name}} | pm2"
  command: pm2 save
  args:
    chdir: "{{ datamapping_base_dir}}"
  ignore_errors: true

- name: "datamapping | {{datamapping_name}} | create dir {{ datamapping_base_dir}}"
  become: true
  file:
    path: "{{ datamapping_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "datamapping | {{datamapping_name}} | create dir {{ datamapping_base_dir}}"
  become: true
  file:
    path: "{{ datamapping_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "datamapping | {{datamapping_name}} | create dir {{ datamapping_build_dir}}"
  become: true
  file:
    path: "{{ datamapping_build_dir}}"
    state: absent
  when: clean_install|bool

- name: "datamapping | {{datamapping_name}} | create dir {{ datamapping_build_dir}}"
  become: true
  file:
    path: "{{ datamapping_build_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "datamapping | {{datamapping_name}} | git checkout {{datamapping_repo}}"
  git:
    repo: "{{datamapping_repo}}"
    dest: "{{ datamapping_base_dir}}"
    force: true

- name: "datamapping | {{datamapping_name}} | Install {{ datamapping_base_dir}} packages"
  npm:
    path: "{{ datamapping_base_dir}}"
    global: no
    state: latest

- name: "datamapping | {{datamapping_name}} | env | copy {{ datamapping_env }} to {{ datamapping_base_dir}}/.env lanes {{ pool_lane_count }}"
  template:
    src: "{{ datamapping_env }}"
    dest: "{{ datamapping_base_dir}}/.env"

- name: "datamapping | {{datamapping_name}} | pm2 start"
  command: pm2 start app.js --name "{{ datamapping_name }}" -f
  args:
    chdir: "{{ datamapping_base_dir}}"

- name: "datamapping | {{datamapping_name}} | pm2"
  command: pm2 save
  args:
    chdir: "{{ datamapping_base_dir}}"


# install -v -m 744 files/colorado.service "${ROOTFS_DIR}/etc/systemd/system"