- hosts: all
  roles:
    - datamapping
    - displaysocket # aktuelle Version
    # - displaysocket2 # geht erst mal nicht
    - nginx 
    - nginxfrontends
    - resultdata
    # - nuvoledwebsocket
    - s3sync
    # - serial
    - osm6
    # - frontend2 # fü sync creation
    # - displayweb # install direct
    # - frontend2 # for sync to aws


    
    