- hosts: all
  roles:
    #- displayweb
    #- displaylive
    - cameroverlay
    # - frontend
    #- adminweb
    ## backend
    # - datamapping
    # - displaysocket
    #- cassandra
    # - datahub
    ## rest
    #- raspberry
    #  common
    #- serial-sender
    #- serial
    #- serialsw
    ## off
    # - serviceoff
    - nginx
    # - simplepeer


# for cloud addons -
# ansible-playbook -i inventories/production/hosts testService.yml --limit=rpi -e mapper_cloud=true