- name: serial-sender | set vars
  set_fact:
    key_value: serial-sender_data
    serial_sender_base_dir: /opt/serial-sender/source
    serial_sender_build_dir: /opt/serial-sender/build
    pogio_master_file: pigpio-master.zip
    pigpio_base_dir: /opt/serial-sender/pigpio

- name: "serial-sender | create dir {{ serial_sender_build_dir}}"
  become: true
  file:
    path: "{{ serial_sender_base_dir}}"
    state: absent

- name: "serial_sender | create dir {{ serial_sender_base_dir}}"
  become: true
  file:
    path: "{{ serial_sender_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "serial-sender | create dir {{ serial_sender_build_dir}}"
  become: true
  file:
    path: "{{ serial_sender_build_dir}}"
    state: absent

- name: "serial-sender | create dir {{ serial_sender_build_dir}}"
  become: true
  file:
    path: "{{ serial_sender_build_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: serial-sender | git checkout
  git:
    repo: https://github.com/hias222/serial-sender.git
    dest: "{{ serial_sender_base_dir}}"

- name: "serial-sender | create dir {{ pigpio_base_dir}}"
  become: true
  file:
    path: "{{ pigpio_base_dir}}"
    owner: root
    group: root
    state: directory
    mode: '0755'
  when: install_gpio_libs|bool

- name: serial-sender | copy pigpio
  become: true 
  unarchive:
    src: "{{ pogio_master_file }}"
    dest: "{{pigpio_base_dir}}"
  when: install_gpio_libs|bool

- name: "serial-sender | install pigpio"
  become: true
  shell: | 
    cd {{pigpio_base_dir}}/pigpio-master
    make
    make install
  when: install_gpio_libs|bool

- name: "serial-sender | build serial-sender"
  shell: | 
    cd {{serial_sender_build_dir}}
    cmake {{serial_sender_base_dir}}
    cmake --build {{serial_sender_build_dir}}

- name: "serial-sender | test.txt "
  template:
    src: test.txt
    dest: "{{serial_sender_build_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0644'
