# npm and cassandra bins install with global true
global_clean_all: true
npm_gloabal_install: no
install_gpio_libs: false
use_ftdi_serial: true
# install_user_os: ubuntu -- ansible_facts.user_id
nginx_server_name: ubuntu
nginx_live_dir: /usr/share/nginx/html/live
nginx_display_dir: /usr/share/nginx/html/display
nginx_frontend_dir: /usr/share/nginx/html/frontend
nginx_admin_dir: /usr/share/nginx/html/admin
nginx_html_dir: /usr/share/nginx/html
nginx_peer_dir: /usr/share/nginx/html/peer
cassandra_base_dir: /opt/cassandra
cassandra_file: apache-cassandra-3.11.7
nginx_domain_name: ubuntu