- name: "laufanzeiger | {{laufanzeiger_name}} | delete dir {{ laufanzeiger_base_dir}}"
  become: true
  file:
    path: "{{ laufanzeiger_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "laufanzeiger | {{laufanzeiger_name}} | create dir {{ laufanzeiger_base_dir}}"
  become: true
  file:
    path: "{{ laufanzeiger_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: laufanzeiger | disable service laufanzeiger
  become: true
  service:
    name: laufanzeiger
    enabled: no
  ignore_errors: true

- name: laufanzeiger | Stop service laufanzeiger
  become: true
  service:
    name: laufanzeiger
    state: stopped
  ignore_errors: true

- name: "laufanzeiger | {{laufanzeiger_name}} | delete dir {{ laufanzeiger_build_dir}}"
  become: true
  file:
    path: "{{ laufanzeiger_build_dir}}"
    state: absent
  when: clean_install|bool

- name: "laufanzeiger | {{laufanzeiger_name}} | create dir {{ laufanzeiger_build_dir}}"
  become: true
  file:
    path: "{{ laufanzeiger_build_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "laufanzeiger | {{laufanzeiger_name}} | git checkout {{laufanzeiger_repo}}"
  git:
    repo: "{{laufanzeiger_repo}}"
    dest: "{{ laufanzeiger_base_dir}}"
    force: true

- name: "laufanzeiger | go build "
  ansible.builtin.shell: go build main.go
  args:
    chdir: "{{ laufanzeiger_base_dir}}"

- name: "laufanzeiger | cp "
  become: true
  shell: | 
    chmod a+rwx {{ laufanzeiger_base_dir }}/main
    cp {{ laufanzeiger_base_dir }}/main /usr/bin/laufanzeiger


- name: "laufanzeiger | install service for laufanzeiger "
  become: true
  template:
    src: laufanzeiger.service
    dest: /lib/systemd/system/laufanzeiger.service
    owner: root
    group: root
    mode: '0644'