- name: "datastore | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: serial_data
    clean_install: "{{global_clean_all}}"
    datastore_base_dir: /opt/datastore/base
    datastore_build_dir: /opt/datastore/build
    datastore_repo: https://github.com/hias222/datastore.git
    datastore_name: datastore
    datastore_env: local

- name: "datastore | set aws "
  set_fact:
    datastore_env: aws.env
  when: aws_install|bool

- name: "datastore | pm2"
  command: pm2 delete app.js --name "{{ datastore_name }}"
  args:
    chdir: "{{ datastore_base_dir}}"
  ignore_errors: true

- name: "datastore | pm2"
  command: pm2 save
  args:
    chdir: "{{ datastore_base_dir}}"
  ignore_errors: true

- name: "datastore | create dir {{ datastore_base_dir}}"
  become: true
  file:
    path: "{{ datastore_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "datastore | create dir {{ datastore_base_dir}}"
  become: true
  file:
    path: "{{ datastore_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "datastore | create dir {{ datastore_build_dir}}"
  become: true
  file:
    path: "{{ datastore_build_dir}}"
    state: absent
  when: clean_install|bool

- name: "datastore | create dir {{ datastore_build_dir}}"
  become: true
  file:
    path: "{{ datastore_build_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "datastore | git checkout {{datastore_repo}}"
  git:
    repo: "{{datastore_repo}}"
    dest: "{{ datastore_base_dir}}"
    force: true

- name: "datastore | Install {{ datastore_base_dir}} packages"
  npm:
    path: "{{ datastore_base_dir}}"
    global: false
    state: latest

- name: "datastore | env | copy environment"
  template:
    src: "{{ datastore_env }}"
    dest: "{{ datastore_base_dir}}/.env"

- name: "datastore | pm2 start"
  command: pm2 start app.js --name "{{ datastore_name }}" -f
  args:
    chdir: "{{ datastore_base_dir}}"

- name: "datastore | pm2"
  command: pm2 save
  args:
    chdir: "{{ datastore_base_dir}}"


# install -v -m 744 files/colorado.service "${ROOTFS_DIR}/etc/systemd/system"
