- name: "cassandra | install"
  debug:
    msg: "start"

- name: "cassandra | pm2 stop all"
  command: pm2 stop all

- name: "cassandra | set args | clean is {{global_clean_all}}"
  set_fact:
    key_value: npm
    os_install_user: "{{ ansible_facts.user_id }}"
    clean_install: "{{global_clean_all}}"

- name: "cassandra | apt update "
  become: true
  apt:
    update_cache: yes
  when: clean_install|bool

- name: "cassandra | install packages "
  become: true
  apt:
    pkg:
    - openjdk-8-jdk
  when: clean_install|bool

- name: cassandra | Stop service cassandra
  become: true
  service:
    name: cassandra
    state: stopped
  ignore_errors: true
  
- name: cassandra | Disable service cassandra
  become: true
  service:
    name: cassandra
    enabled: no
  ignore_errors: true
    
- name: cassandra | remove service cassandra
  become: true 
  file:
    path: /etc/systemd/system/cassandra.service
    state: absent

- name: cassandra | reload systemd
  become: true
  shell: | 
    systemctl daemon-reload

- name: "cassandra | remove dir {{cassandra_base_dir}}"
  become: true
  file:
    path: "{{ cassandra_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "cassandra | create dir {{ cassandra_base_dir}}"
  become: true
  file:
    path: "{{ cassandra_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "cassandra | extract {{ cassandra_base_dir }}"
  unarchive:
    src: "{{ cassandra_file }}-bin.tar.gz"
    dest: "{{cassandra_base_dir}}"
  when: clean_install|bool

- name: "cassandra | install service "
  become: true
  template:
    src: cassandra.service
    dest: /lib/systemd/system/cassandra.service
    owner: root
    group: root
    mode: '0644'

- name: cassandra | reload systemd
  become: true
  shell: | 
    systemctl daemon-reload

- name: cassandra | Enable service cassandra
  become: true
  service:
    name: cassandra
    enabled: yes

- name: cassandra | start service cassandra
  become: true
  service:
    name: cassandra
    state: started

- name: "cassandra | pm2 start all"
  command: pm2 start all