- name: "displayweb | nginx | copy environment"
  become: true
  template:
    src: default
    dest: "{{ nginx_config_dir}}"

- name: "displayweb | nginx | copy index"
  become: true
  template:
    src: index.html
    dest: "{{ nginx_html_dir}}"

- name: displayweb | nginx | Enable service nginx
  become: true
  service:
    name: nginx
    enabled: yes

- name: displayweb | nginx | Restart service nginx
  become: true
  service:
    name: nginx
    state: restarted