- name: "swimmenu | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: swimmenu_data
    arm_architecture: true
    clean_install: "{{global_clean_all}}"
    swimmenu_base_dir: /opt/swimmenu/base
    swimmenu_repo: https://github.com/hias222/swimmenu.git

- name: swimmenu | Stop service cassandra
  become: true
  service:
    name: cassandra
    state: stopped
  ignore_errors: true

- name: "swimmenu | set args for x86_64"
  set_fact: 
    key_value: serial_data
    arm_architecture: false
  when: ansible_architecture=='x86_64'

- name: "swimmenu | remove dir {{swimmenu_base_dir}}"
  become: true
  file:
    path: "{{ swimmenu_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "swimmenu | pm2 stop all"
  command: pm2 stop all
  ignore_errors: true

- name: "swimmenu | create dir {{ swimmenu_base_dir}}"
  become: true
  file:
    path: "{{ swimmenu_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "swimmenu | create dir {{ nginx_swimmenu_dir}}"
  become: true
  file:
    path: "{{ nginx_swimmenu_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "swimmenu | git checkout {{swimmenu_repo}}"
  git:
    repo: "{{swimmenu_repo}}"
    dest: "{{ swimmenu_base_dir}}"
    force: yes

- name: "swimmenu | gatsby-config | copy "
  template:
    src: gatsby-config.js
    dest: "{{ swimmenu_base_dir }}/gatsby-config.js"

- name: "swimmenu | common | autoconf, libtool etc. needed for gatsby mozjpeg@7.0.0"
  become: true
  apt:
    pkg:
    - autoconf
    - libtool
    - pkg-config 
    - nasm
    - dpkg
    - libpng-dev
    - g++
    #nasm autoconf automake libtool dpkg pkgconfig libpng libpng-dev g+

- name: "swimmenu | update npm install -g gatsby-cli "
  shell: 
    cmd: npm install -g gatsby-cli
    chdir: "{{ swimmenu_base_dir}}"

- name: swimmenu "gatsby-cli" node.js package globally (npm install -g gatsby-cli).
  community.general.npm:
    name: gatsby-cli
    global: yes

- name: "swimmenu | Install {{ swimmenu_base_dir}} packages"
  npm:
    path: "{{ swimmenu_base_dir}}"
    global: "{{ npm_gloabal_install }}"
    state: latest
    
- name: "swimmenu | build {{ swimmenu_base_dir}}"
  shell: 
    cmd: gatsby build --prefix-paths
    chdir: "{{ swimmenu_base_dir}}"

- name: "swimmenu | cp {{swimmenu_base_dir}}/public/* to  {{nginx_swimmenu_dir}}"
  become: true
  shell: cp -rf {{swimmenu_base_dir}}/public/* {{nginx_swimmenu_dir}}

- name: "swimmenu | pm2 start all"
  command: pm2 start all
  ignore_errors: true

- name: swimmenu | Stop service cassandra
  become: true
  service:
    name: cassandra
    state: restarted
  ignore_errors: true