- name: "camera | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: serial_data
    clean_install: "{{global_clean_all}}"
    camera_base_dir: /opt/camera/camera
    arm_architecture: true
    camera_repo: https://github.com/hias222/webcam.git

- name: "camera | remove dir {{camera_base_dir}}"
  become: true
  file:
    path: "{{ camera_base_dir}}"
    state: absent
  when: clean_install|bool

- name: displayweb | Stop service cassandra
  become: true
  service:
    name: cassandra
    state: stopped
  ignore_errors: true

- name: "camera | create dir {{ camera_base_dir}}"
  become: true
  file:
    path: "{{ camera_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "camera | create dir {{ nginx_camera_dir}}"
  become: true
  file:
    path: "{{ nginx_camera_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "camera | git checkout {{camera_repo}}"
  git:
    repo: "{{camera_repo}}"
    dest: "{{ camera_base_dir}}"
    force: yes

- name: "camera | cp {{camera_base_dir}}/camera/* to  {{nginx_camera_dir}}"
  become: true
  shell: cp -rf {{camera_base_dir}}/camera/* {{nginx_camera_dir}}

- name: camera | start service cassandra
  become: true
  service:
    name: cassandra
    state: started
  ignore_errors: true

- name: "camera | pm2 start all"
  command: pm2 start all
  ignore_errors: true