- name: "simplepeer | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: serial_data
    clean_install: "{{global_clean_all}}"
    simplepeer_base_dir: /opt/simplepeer/base
    simplepeer_build_dir: /opt/simplepeer/build
    simplepeer_repo: https://github.com/hias222/webcam.git

- name: "simplepeer | pm2 | remove simplepeer"
  command: pm2 delete  simplepeer
  args:
    chdir: "{{ simplepeer_base_dir}}"
  ignore_errors: true

- name: "simplepeer | pm2 | save state"
  command: pm2 save
  args:
    chdir: "{{ simplepeer_base_dir}}"
  ignore_errors: true

- name: "simplepeer | create dir {{ simplepeer_base_dir}}"
  become: true
  file:
    path: "{{ simplepeer_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "simplepeer | create dir {{ simplepeer_base_dir}}"
  become: true
  file:
    path: "{{ simplepeer_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "simplepeer | create dir {{ simplepeer_build_dir}}"
  become: true
  file:
    path: "{{ simplepeer_build_dir}}"
    state: absent
  when: clean_install|bool

- name: "simplepeer | create dir {{ simplepeer_build_dir}}"
  become: true
  file:
    path: "{{ simplepeer_build_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "simplepeer | git checkout {{simplepeer_repo}}"
  git:
    repo: "{{simplepeer_repo}}"
    dest: "{{ simplepeer_base_dir}}"
    force: true

- name: "simplepeer | Install {{ simplepeer_base_dir}} packages"
  npm:
    path: "{{ simplepeer_base_dir}}/server"
    global: "{{ npm_gloabal_install }}"
    state: latest

- name: "simplepeer | pm2 start"
  command: pm2 start server.js --name simplepeer -f
  args:
    chdir: "{{ simplepeer_base_dir}}/server"

- name: "simplepeer | pm2"
  command: pm2 save
  args:
    chdir: "{{ simplepeer_base_dir}}"

- include_tasks: client.yml

- include_tasks: camera.yml