- name: colorado | disable service colorado
  become: true
  service:
    name: colorado
    enabled: no
  ignore_errors: true

- name: "colorado | disable service pm2-{{ install_user_os }}"
  become: true
  service:
    name: "pm2-{{ install_user_os }}"
    enabled: no
  ignore_errors: true

- name: datahub | Stop service cassandra
  become: true
  service:
    name: cassandra
    state: restarted
  ignore_errors: true

- name: "colorado | disable service pm2-{{ install_user_os }}"
  become: true
  service:
    name: cassandra
    enabled: no
  ignore_errors: true

- name: "colorado | reboot"
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

