- name: "adminweb | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: adminweb
    arm_architecture: true
    clean_install: "{{global_clean_all}}"
    adminweb_base_dir: /opt/adminweb/base
    adminweb_repo: https://github.com/hias222/adminweb.git

- name: adminweb | Stop service cassandra
  become: true
  service:
    name: cassandra
    state: stopped
  ignore_errors: true

- name: "adminweb | set args for x86_64"
  set_fact: 
    key_value: adminweb
    arm_architecture: false
  when: ansible_architecture=='x86_64'

- name: "adminweb | remove dir {{adminweb_base_dir}}"
  become: true
  file:
    path: "{{ adminweb_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "adminweb | pm2 stop all"
  command: pm2 stop all
  ignore_errors: true

- name: adminweb | Stop service mosquitto.service
  become: true
  service:
    name: mosquitto
    state: stopped
  ignore_errors: true

- name: "adminweb | create dir {{ adminweb_base_dir}}"
  become: true
  file:
    path: "{{ adminweb_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "adminweb | create dir {{ nginx_admin_dir}}"
  become: true
  file:
    path: "{{ nginx_admin_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "adminweb | git checkout {{adminweb_repo}}"
  git:
    repo: "{{adminweb_repo}}"
    dest: "{{ adminweb_base_dir}}"
    force: yes

#- name: "adminweb | Install {{ adminweb_base_dir}} packages"
#  npm:
#    path: "{{ adminweb_base_dir}}"
#    state: latest
- name: "adminweb | Install {{ adminweb_base_dir}} packages"
  shell: 
    cmd: npm install
    chdir: "{{ adminweb_base_dir}}"

- name: "adminweb | env | copy environment"
  template:
    src: .env
    dest: "{{ adminweb_base_dir}}"

- name: "adminweb | build {{ adminweb_base_dir}}"
  shell: 
    cmd: npm run build
    chdir: "{{ adminweb_base_dir}}"
  

- name: "adminweb | mv {{adminweb_base_dir}} to  {{nginx_admin_dir}}"
  become: true
  shell: cp -rf {{adminweb_base_dir}}/build/* {{nginx_admin_dir}}

- name: adminweb | Restart service cassandra
  become: true
  service:
    name: cassandra
    state: restarted
  ignore_errors: true

- name: adminweb | Restart service mosquitto.service
  become: true
  service:
    name: mosquitto
    state: restarted
  ignore_errors: true

- name: "adminweb | pm2 start all"
  command: pm2 start all
  ignore_errors: true