- name: "nginx | frontend | create dir {{ frontends_dir }}/data"
  become: true
  file:
    path: "{{ frontends_dir }}/data"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'

- name: "nginx | frontend copy example.png"
  become: true
  ansible.builtin.copy:
    src: "files/example.png"
    dest: "{{ frontends_dir }}/data"
    mode: '0755'
