- name: "common | install base | global_clean_all {{global_clean_all}}"
  debug: 
    msg: "install base"

- name: "common | set args"
  set_fact:
    key_value: npm
    clean_install: "{{global_clean_all}}"
    npm_download_file: node-v12.18.3-linux-arm64

- name: "common | set args for x86_64"
  set_fact: 
    key_value: npm
    npm_download_file: node-v12.18.3-linux-x64
  when: ansible_architecture=='x86_64'

- name: "common | apt update "
  become: true
  apt:
    update_cache: yes

- name: "common | install packages "
  become: true
  apt:
    pkg:
    - gcc
    - git
    - build-essential
    - make
    - cmake
    - unzip
    # - python-setuptools 
    - python3-setuptools
    - libssl-dev
    - jpnevulator
    - mosquitto 
    - mosquitto-clients
    - nginx-full

- name: "common | create dir {{ npm_download_file}}"
  become: true
  file:
    path: "/opt/{{ npm_download_file}}"
    state: absent
  when: clean_install|bool

- name: "common | create dir {{ npm_download_file}}"
  become: true
  file:
    path: "/opt/{{ npm_download_file}}"
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'

- name: "common | npm | extract {{ npm_download_file }}"
  unarchive:
    src: "{{ npm_download_file }}.tar.xz"
    dest: /opt
  when: clean_install|bool

- name: "common | npm | copy environment"
  become: true
  template:
    src: environment
    dest: /etc/environment

- name: "common | npm | reset ssh connection"
  meta: reset_connection

- name: "common | npm | run node -v"
  shell: node -v
  register: shell_output

- name: "common | check npm"
  debug: 
    msg: "{{shell_output.stdout_lines}}"
