- name: "common | install base | global_clean_all {{global_clean_all}}"
  debug: 
    msg: "install base {{ ansible_architecture }}"

- name: "common | set args"
  set_fact:
    key_value: npm
    arm_architecture: true
    clean_install: "{{global_clean_all}}"
    npm_download_file: node-v14.15.3-linux-arm64

- name: "common | set args for x86_64"
  set_fact: 
    key_value: npm
    arm_architecture: false
    npm_download_file: node-v12.18.3-linux-x64
  when: ansible_architecture=='x86_64'

- name: "common | set args for armv7l"
  set_fact: 
    key_value: npm
    arm_architecture: false
    npm_download_file: node-v12.18.3-linux-armv7l
  when: ansible_architecture=='armv7l'

- name: "common | apt update "
  become: true
  apt:
    update_cache: yes

- name: "common | remove snap"
  become: true
  shell: | 
    snap remove lxd
    snap remove core18
    snap remove snapd
  when: 
    - arm_architecture|bool 
    - clean_install|bool
  ignore_errors: true

- name: "common | reboot"
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: 
    - arm_architecture|bool 
    - clean_install|bool

- name: "common | install node-sass"
  npm:
    name: node-sass
    state: latest
    global: true
  when: 
    - arm_architecture|bool 
    - clean_install|bool
  ignore_errors: true

- name: "common | compile sass"
  command: npm rebuild node-sass
  when: 
    - arm_architecture|bool 
    - clean_install|bool

- name: "common | install packages "
  become: true
  apt:
    pkg:
    - gcc
    - git
    - build-essential
    - make
    - cmake
    - unzip
    # - python-setuptools 
    - python3-setuptools
    - libssl-dev
    - jpnevulator
    - mosquitto 
    - mosquitto-clients
    - nginx-full

- name: "common | install python2.7 for cassandra "
  become: true
  apt:
    pkg:
    - python2.7

- name: "common | install python node-sass "
  become: true
  apt:
    pkg:
    - python

- name: "common | create dir {{ npm_download_file}}"
  become: true
  file:
    path: "/opt/{{ npm_download_file}}"
    state: absent
  when: clean_install|bool

- name: "common | create dir {{ npm_download_file}}"
  become: true
  file:
    path: "/opt/{{ npm_download_file}}"
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'

- name: "common | npm | extract {{ npm_download_file }}"
  unarchive:
    src: "{{ npm_download_file }}.tar.xz"
    dest: /opt
  when: clean_install|bool

- name: "common | npm | copy environment"
  become: true
  template:
    src: environment
    dest: /etc/environment

- name: "common | npm | reset ssh connection"
  meta: reset_connection

- name: "common | npm | run node -v"
  shell: node -v
  register: shell_output

- name: "common | check npm"
  debug: 
    msg: "{{shell_output.stdout_lines}}"

- name: "common | npm pm2 global"
  npm:
    name: pm2
    global: yes

- name: "common | npm node-sass global"
  npm:
    name: node-sass
    global: yes

- name: "common | delete pm2 folder /home/{{ install_user_os }}/.pm2"
  become: true
  file:
    path: "/home/{{ install_user_os }}/.pm2"
    state: absent
  when: clean_install|bool
  ignore_errors: true

- name: "common | npm | reset ssh connection"
  meta: reset_connection

- name: "common | start pm2 | prepare scripts"
  command: pm2 startup ubuntu -u {{ install_user_os }} --hp /home/{{ install_user_os }}
  when: clean_install|bool
  ignore_errors: true

- name: "common | start pm2 | /opt/{{ npm_download_file}}/bin"
  command: sudo env PATH=$PATH:/opt/{{ npm_download_file}}/bin pm2 startup ubuntu -u {{ install_user_os }} --hp /home/{{ install_user_os }}
  register: output
  when: clean_install|bool

# become_user: root
# become_method: enable
# /opt/{{ npm_download_file}}/bin/pm2 startup {{ install_user_os }} -u {{ install_user_os }} --hp /home/{{ install_user_os }}
# sudo env PATH=$PATH:/opt/node-v12.18.3-linux-x64/bin pm2 startup ubuntu -u ubuntu --hp /home/ubuntu"]}

- name: common | debug 
  debug:
    msg: "{{output.stdout}}"
  when: clean_install|bool

- name: "common | disable service pm2-{{ install_user_os }}"
  become: true
  service:
    name: "pm2-{{ install_user_os }}"
    enabled: yes
  ignore_errors: true