- name: "common | changeRPIstart"
  debug: 
    msg: "install base"

- name: "common | changeRPIstart | copy nobtcmd.txt"
  become: true
  copy:
    src: nobtcmd.txt
    dest: /boot/firmware/nobtcmd.txt
    owner: root
    group: root
    mode: '0755'
     
- name: "common | changeRPIstart | copy usercfg.txt"
  become: true
  copy:
    src: usercfg.txt
    dest: /boot/firmware/usercfg.txt
    owner: root
    group: root
    mode: '0755'

- name: "common | changeRPIstart | reboot"
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami