- name: "common | install base"
  debug: 
    msg: "install base"

- name: "common | set args"
  set_fact:
    key_value: npm

- name: "common add changeRPIstart"
  include_tasks: changeRPIstart.yml
  when: install_gpio_libs|bool

- name: "common | apt update "
  become: true
  apt:
    update_cache: yes

- name: "common | install packages "
  become: true
  apt:
    pkg:
    - gcc
    - build-essential
    - make
    - cmake
    - unzip
    - python-setuptools 
    - python3-setuptools
    - libssl-dev
    - jpnevulator
    - mosquitto 
    - mosquitto-clients
    - nginx-full

