- name: "displaysocket | set vars | global_clean_all {{global_clean_all}}"
  set_fact:
    key_value: serial_data
    clean_install: "{{global_clean_all}}"
    displaysocket_base_dir: /opt/displaysocket/base
    displaysocket_repo: https://github.com/hias222/displaysocket.git

- name: "displaysocket | npm pm2 global"
  npm:
    name: pm2
    global: yes

- name: "displaysocket | ufw allow 4001"
  become: true
  shell: 
    cmd: ufw allow 4001
  ignore_errors: true
    
- name: "displaysocket | pm2"
  command: pm2 delete app.js --name displaysocket
  args:
    chdir: "{{ displaysocket_base_dir}}"
  ignore_errors: true
  
- name: "displaysocket | pm2"
  command: pm2 save
  args:
    chdir: "{{ displaysocket_base_dir}}"
  ignore_errors: true

- name: "displaysocket | remove dir {{ displaysocket_base_dir}}"
  become: true
  file:
    path: "{{ displaysocket_base_dir}}"
    state: absent
  when: clean_install|bool

- name: "displaysocket | create dir {{ displaysocket_base_dir}}"
  become: true
  file:
    path: "{{ displaysocket_base_dir}}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    state: directory
    mode: '0755'


- name: "displaysocket | git checkout {{displaysocket_repo}}"
  git:
    repo: "{{displaysocket_repo}}"
    dest: "{{ displaysocket_base_dir}}"
    force: true

- name: "displaysocket | Install {{ displaysocket_base_dir}} packages"
  npm:
    path: "{{ displaysocket_base_dir}}"
    global: "{{ npm_gloabal_install }}"
    state: latest

- name: "displaysocket | env | copy environment"
  template:
    src: .env
    dest: "{{ displaysocket_base_dir}}"
  when: not aws_install|bool

- name: "displaysocket | set aws "
  template:
    src: aws.env
    dest: "{{ displaysocket_base_dir}}/.env"
  when: aws_install|bool

- name: "displaysocket | pm2"
  command: pm2 start app.js --name displaysocket
  args:
    chdir: "{{ displaysocket_base_dir}}"

- name: "displaysocket | pm2"
  command: pm2 save
  args:
    chdir: "{{ displaysocket_base_dir}}"


# install -v -m 744 files/colorado.service "${ROOTFS_DIR}/etc/systemd/system"
